<a href="https://colab.research.google.com/github/naveen09peesari/cpp/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Python program for
# Creation of Arrays
import numpy as np
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [7]:
import numpy as np
List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
npList = np.array(List)
n = len(npList)
for i in range(n):
    print(npList[i])
#printing an array
a = int(input("Enter a number: "))
b = np.array([1, 2, 3, 4, 5])
b_list = b.tolist()
b_list.append(a)
b = np.array(b_list)
print(b)
#identifing the types
A = "Hello, world!"
variable = 42
float= 3.14
list = [1, 2, 3]
array = np.array([1, 2, 3])
print("Type of string_variable:", type(A))
print("Type of variable:", type(variable))
print("Type of float:", type(float))
print("Type of list:", type(list))
print("Type of array:", type(array))
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
mul_result = a * b
print(f"{a} * {b} = {mul_result}")
div_result = a / b
print(f"{a} / {b} = {div_result}")
pow_result = a ** b
print(f"{a} ** {b} = {pow_result}")
#combine text with numpy function to generate a textual output addition of two array1 and array2
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
result = array1 + array2
textual_output = (
    f"Array 1: {array1}\n"
    f"Array 2: {array2}\n"
    f"Addition of Array 1 and Array 2:\n"
    f"{result}"
)
print(textual_output)
x = 2.0
sin_x = np.sin(x)
print(f"sin({x}) = {sin_x}")
log_x = np.log(x)
print(f"log({x}) = {log_x}")
log2_x = np.log2(x)
print(f"log2({x}) = {log2_x}")
exp_x = np.exp(x)
print(f"exp({x}) = {exp_x}")

1
2
3
4
5
6
7
8
9
Enter a number: 2
[1 2 3 4 5 2]
Type of string_variable: <class 'str'>
Type of variable: <class 'int'>
Type of float: <class 'float'>
Type of list: <class 'list'>
Type of array: <class 'numpy.ndarray'>
Enter a number: 4
Enter a number: 5
4 * 5 = 20
4 / 5 = 0.8
4 ** 5 = 1024
Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Addition of Array 1 and Array 2:
[ 6  8 10 12]
sin(2.0) = 0.9092974268256817
log(2.0) = 0.6931471805599453
log2(2.0) = 1.0
exp(2.0) = 7.38905609893065


In [2]:
print("naveen")

naveen
